### PR TITLE
enable `npm test`

### PR DESCRIPTION
**Pull request by harlantwood**

### CODE REVIEW

**Comment by bion** [comment]
thanks! we're avoiding using globally installed packages though, so for this to work i think it'd need to be

```
./node_modules/.bin/mocha
```

**Comment by harlantwood** [comment]
Nope!  Node magic does that for you :)

**Comment by bion** [comment]
hmmm, maybe NVM is causing a problem? after making the change:
screen shot 2016-01-21 at 12 57 54 pm

**Comment by harlantwood** [comment]
Hm, your error said invalid json.  Were you missing a comma or quote by chance?  

I'm also using nvm, don't think it's that

**Comment by bion** [comment]
@harlantwood yep :sheep:

**Comment by harlantwood** [comment]
Best use of sheepicon ever

**Pull request merged**
